#!/usr/bin/env bash
set -e

export rvm_trust_rvmrcs_flag=1
DIR="$( cd "$( dirname "$0" )" && pwd )"

if [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  source "/usr/local/rvm/scripts/rvm"
elif [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  source "$HOME/.rvm/scripts/rvm"
fi

cd "$DIR"

if [[ -n "$RAILS_ENV" ]] ; then
  export RACK_ENV=$RAILS_ENV
  export RAILS_ENV=$RAILS_ENV
elif [[ -n "$RACK_ENV" ]] ; then
  export RACK_ENV=$RACK_ENV
  export RAILS_ENV=$RACK_ENV
else
  export RACK_ENV=production
  export RAILS_ENV=production
fi

exec bin/unicorn -c "$DIR/config/unicorn.rb" -E "$RACK_ENV" -D
